version: '3.8'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: A
    networks:
      - backend
  app:
    image: raulnicoletti/docker-app:latest
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - "postgres"

networks:
  backend:
    driver: bridge
